name: CalculatorUI
main: Wallypacmero\CalculatorUI\Main
load: POSTWORLD
version: 1.0.0-beta
api: 3.0.0
author: 
- WallyPacmero
- NaufanBlaze

commands:
  cal:
   description: "CalculatorUI Commands"
   permission: calculatorui.command
   usage: /cal

permissions:
  calculatorui.command:
    default: op
    description: "CalculatorUI Commands"
